# Generated by Django 5.1.2 on 2024-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_agency_office_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(unique=True)),
                ('agent_license', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_url', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_office_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_office_fax', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_address', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
