# Generated by Django 5.1.2 on 2024-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(default='New', max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
