# Generated by Django 5.1.2 on 2024-10-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=500, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('st_count', models.IntegerField(blank=True, null=True)),
                ('agency_id', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_phones', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_email', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_banner', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_link', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_type_id', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_creator_id', models.CharField(blank=True, max_length=500, null=True)),
                ('has_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_ver', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_st_count', models.CharField(blank=True, max_length=500, null=True)),
                ('address_geo', models.CharField(blank=True, max_length=500, null=True)),
                ('address_eng', models.CharField(blank=True, max_length=500, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_json', models.JSONField()),
                ('agency_json', models.JSONField()),
                ('status', models.CharField(default='New', max_length=4)),
            ],
        ),
    ]
