# Generated by Django 5.1.2 on 2024-11-10 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(unique=True)),
                ('business_type', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_сount', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('read_more_url', models.CharField(blank=True, max_length=500, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=500, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=500, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=500, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('categories', models.CharField(blank=True, max_length=500, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=500, null=True)),
                ('yelp_menu', models.CharField(blank=True, max_length=500, null=True)),
                ('operation_hours', models.CharField(blank=True, max_length=500, null=True)),
                ('chain_biz_info', models.CharField(blank=True, max_length=500, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('status', models.CharField(default='New', max_length=500)),
                ('json_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
