# Generated by Django 5.1.2 on 2024-11-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='review_сount',
            new_name='review_count',
        ),
    ]
