# Generated by Django 5.1.2 on 2024-11-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_review_сount_business_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decs', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='New', max_length=500)),
            ],
            options={
                'unique_together': {('decs', 'category', 'postal_code')},
            },
        ),
    ]
