# Generated by Django 5.1.2 on 2024-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_searchwitoutcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='json_data_search',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
