# Generated by Django 5.1.2 on 2024-11-14 12:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_business_json_data_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='start_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='start_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='start_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='start_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='start_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(blank=True, max_length=500, null=True)),
                ('author_total_count_reviews', models.IntegerField(blank=True, null=True)),
                ('author_is_elite', models.BooleanField(blank=True, null=True)),
                ('count_thanks_reactions', models.IntegerField(blank=True, null=True)),
                ('count_useful_reactions', models.IntegerField(blank=True, null=True)),
                ('count_love_this_reactions', models.IntegerField(blank=True, null=True)),
                ('count_oh_no_reactions', models.IntegerField(blank=True, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('json_data', models.JSONField()),
                ('status', models.CharField(default='New', max_length=500)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.business', to_field='business_id')),
            ],
        ),
    ]
