# Generated by Django 5.1.2 on 2024-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_business_start_1_business_start_2_business_start_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
