# Generated by Django 5.1.2 on 2024-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_review_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='business_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
