# Generated by Django 5.1.2 on 2024-11-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_review_business_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
