# Generated by Django 5.1.2 on 2024-11-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='business_id',
            new_name='business',
        ),
    ]
