# Generated by Django 5.1.2 on 2024-11-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_rename_business_id_review_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='start_1',
            new_name='stars_1',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='start_2',
            new_name='stars_2',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='start_3',
            new_name='stars_3',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='start_4',
            new_name='stars_4',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='start_5',
            new_name='stars_5',
        ),
    ]
