# Generated by Django 5.1.2 on 2024-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_rename_start_1_business_stars_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rewritten_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
