# Generated by Django 5.1.2 on 2024-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_business_rewritten_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='rewritten_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='year_established',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
