# Generated by Django 5.1.2 on 2024-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_remove_business_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
