# Generated by Django 5.1.2 on 2024-11-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0018_business_json_data_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
