# Generated by Django 5.1.2 on 2024-11-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0019_business_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='rewritten_description_2',
        ),
    ]
