# Generated by Django 5.1.2 on 2024-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=500, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=500, null=True)),
                ('agents', models.JSONField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('conversation_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('conversation_type', models.CharField(blank=True, max_length=500, null=True)),
                ('conversation_status', models.CharField(blank=True, max_length=500, null=True)),
                ('unread_count', models.IntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('highlighted', models.BooleanField(default=False)),
                ('messages', models.JSONField(blank=True, null=True)),
                ('statuses', models.JSONField(blank=True, null=True)),
                ('conversation_json', models.JSONField()),
                ('messages_json', models.JSONField()),
                ('status', models.CharField(default='New', max_length=25)),
            ],
        ),
    ]
