# Generated by Django 5.1.2 on 2024-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_conversationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationdata',
            name='messages_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
