# Generated by Django 5.1.2 on 2024-10-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('agency', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('phone2', models.CharField(blank=True, max_length=500, null=True)),
                ('member_since', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(default='New', max_length=4)),
            ],
        ),
    ]
