# Generated by Django 5.1.2 on 2024-10-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(unique=True)),
                ('json_data', models.JSONField()),
                ('agents_of_excellence_rank', models.IntegerField(blank=True, null=True)),
                ('blog_url', models.CharField(blank=True, max_length=501, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('listing_count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('office_brand_hex_code', models.CharField(blank=True, max_length=500, null=True)),
                ('office_image', models.CharField(blank=True, max_length=500, null=True)),
                ('office_is_brand_colour_light', models.BooleanField(blank=True, null=True)),
                ('office_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_ddi', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=500, null=True)),
                ('show_profile', models.BooleanField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=500, null=True)),
                ('website_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
