# Generated by Django 5.1.2 on 2024-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(unique=True)),
                ('ico', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phones', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.CharField(blank=True, max_length=500, null=True)),
                ('review_count', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_email', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_id', models.IntegerField(blank=True, null=True)),
                ('agency_image', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_website', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_json', models.JSONField()),
                ('agent_json', models.JSONField()),
                ('status', models.CharField(default='New', max_length=500)),
            ],
        ),
    ]
