# Generated by Django 5.1.2 on 2024-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(unique=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_name', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_license', models.CharField(blank=True, max_length=500, null=True)),
                ('rental_license', models.CharField(blank=True, max_length=500, null=True)),
                ('is_phone_revealed', models.BooleanField(blank=True, null=True)),
                ('json_data', models.JSONField()),
                ('status', models.CharField(default='New', max_length=500)),
            ],
        ),
    ]
