# Generated by Django 5.1.2 on 2024-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=500, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=500, null=True)),
                ('email_address', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone_1', models.CharField(blank=True, max_length=500, null=True)),
                ('telephone_2', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('cpa_trading_name', models.CharField(blank=True, max_length=500, null=True)),
                ('websiteurl', models.CharField(blank=True, max_length=500, null=True)),
                ('address_composite', models.CharField(blank=True, max_length=500, null=True)),
                ('address_latitude', models.FloatField(blank=True, null=True)),
                ('address_longitude', models.FloatField(blank=True, null=True)),
                ('json_data', models.JSONField()),
                ('status', models.CharField(default='New', max_length=500)),
            ],
        ),
    ]
