# Generated by Django 5.1.2 on 2024-11-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='account_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('account_id', 'country', 'state')},
        ),
    ]
