# Generated by Django 5.1.2 on 2024-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_extension', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_phone_extension', models.CharField(blank=True, max_length=500, null=True)),
                ('virtual_phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('virtual_phone_extension', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_using_sms', models.BooleanField(blank=True, null=True)),
                ('is_using_whatsapp', models.BooleanField(blank=True, null=True)),
                ('is_allowing_remote_calls', models.BooleanField(blank=True, null=True)),
                ('experience_since', models.IntegerField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=500, null=True)),
                ('locale', models.CharField(blank=True, max_length=500, null=True)),
                ('agency_id', models.IntegerField(blank=True, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=500, null=True)),
                ('account_site', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('addresses', models.CharField(blank=True, max_length=500, null=True)),
                ('recommendations', models.IntegerField(blank=True, null=True)),
                ('facets_buy', models.CharField(blank=True, max_length=500, null=True)),
                ('facets_rent', models.CharField(blank=True, max_length=500, null=True)),
                ('facets_sold', models.CharField(blank=True, max_length=500, null=True)),
                ('folowers', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
