# Generated by Django 5.1.2 on 2024-11-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(default='New', max_length=500),
        ),
    ]
