# Generated by Django 5.1.2 on 2024-11-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField(unique=True)),
                ('agency_name', models.CharField(blank=True, max_length=500, null=True)),
                ('account_site', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('addresses', models.CharField(blank=True, max_length=500, null=True)),
                ('recommendations', models.IntegerField(blank=True, null=True)),
                ('facets_buy', models.CharField(blank=True, max_length=500, null=True)),
                ('facets_rent', models.CharField(blank=True, max_length=500, null=True)),
                ('facets_sold', models.CharField(blank=True, max_length=500, null=True)),
                ('folowers', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='account_site',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='facets_buy',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='facets_rent',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='facets_sold',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='folowers',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='website',
        ),
        migrations.AddField(
            model_name='agent',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
