# Generated by Django 5.1.2 on 2024-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_agency_remove_agent_account_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='folowers',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='agency',
            name='json_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
