# Generated by Django 5.1.2 on 2024-11-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_rename_folowers_agency_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='facets_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='facets_rent',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='facets_sold',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
